//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceForTatung.SharpWSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sharp.server.ws.v8.imis.tatung.com/", ConfigurationName="SharpWSService.Sharp_WSDelegate")]
    public interface Sharp_WSDelegate {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sharp.server.ws.v8.imis.tatung.com/Sharp_WSDelegate/SendOrderRequest", ReplyAction="http://sharp.server.ws.v8.imis.tatung.com/Sharp_WSDelegate/SendOrderResponse")]
        ServiceForTatung.SharpWSService.SendOrderResponse SendOrder(ServiceForTatung.SharpWSService.SendOrderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendOrder", Namespace="http://sharp.server.ws.v8.imis.tatung.com/", Order=0)]
        public ServiceForTatung.SharpWSService.SendOrderRequestBody Body;
        
        public SendOrderRequest() {
        }
        
        public SendOrderRequest(ServiceForTatung.SharpWSService.SendOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SendOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public SendOrderRequestBody() {
        }
        
        public SendOrderRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendOrderResponse", Namespace="http://sharp.server.ws.v8.imis.tatung.com/", Order=0)]
        public ServiceForTatung.SharpWSService.SendOrderResponseBody Body;
        
        public SendOrderResponse() {
        }
        
        public SendOrderResponse(ServiceForTatung.SharpWSService.SendOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SendOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public SendOrderResponseBody() {
        }
        
        public SendOrderResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Sharp_WSDelegateChannel : ServiceForTatung.SharpWSService.Sharp_WSDelegate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Sharp_WSDelegateClient : System.ServiceModel.ClientBase<ServiceForTatung.SharpWSService.Sharp_WSDelegate>, ServiceForTatung.SharpWSService.Sharp_WSDelegate {
        
        public Sharp_WSDelegateClient() {
        }
        
        public Sharp_WSDelegateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Sharp_WSDelegateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Sharp_WSDelegateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Sharp_WSDelegateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceForTatung.SharpWSService.SendOrderResponse ServiceForTatung.SharpWSService.Sharp_WSDelegate.SendOrder(ServiceForTatung.SharpWSService.SendOrderRequest request) {
            return base.Channel.SendOrder(request);
        }
        
        public string SendOrder(string arg0) {
            ServiceForTatung.SharpWSService.SendOrderRequest inValue = new ServiceForTatung.SharpWSService.SendOrderRequest();
            inValue.Body = new ServiceForTatung.SharpWSService.SendOrderRequestBody();
            inValue.Body.arg0 = arg0;
            ServiceForTatung.SharpWSService.SendOrderResponse retVal = ((ServiceForTatung.SharpWSService.Sharp_WSDelegate)(this)).SendOrder(inValue);
            return retVal.Body.@return;
        }
    }
}
